# Generated by Django 4.1.5 on 2023-01-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gryffindor', max_length=100)),
                ('logo_url', models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqLKGMXNr62iTZjs8oGIOSwOacxjcEP7y8uDNAw8E&s', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Harry', max_length=100)),
                ('last_name', models.CharField(default='Potter', max_length=100)),
                ('school_year', models.CharField(default='Kindergarten', max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', related_query_name='student', to='housepoints.house')),
            ],
        ),
    ]
